"""empty message

Revision ID: e8a2aeda95b4
Revises: d3e0c4015d71
Create Date: 2018-02-11 12:02:19.925592

"""
from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision = 'e8a2aeda95b4'
down_revision = 'd3e0c4015d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('trange', app.helpers.TIMERANGE(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('queue_settings_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['queue_settings_id'], ['queue_setting.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
