"""empty message

Revision ID: f18cc399d88f
Revises: 1ff0a334d40d
Create Date: 2018-02-25 08:58:27.395193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f18cc399d88f'
down_revision = '1ff0a334d40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_board', sa.Column('members', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_board', 'members')
    # ### end Alembic commands ###
